build:
    cmake -B build -DCMAKE_BUILD_TYPE=Debug
    cmake --build build
    ln -sf build/compile_commands.json .

test:
    cmake -B build-test -DCMAKE_BUILD_TYPE=Debug -DENABLE_ASAN=ON
    cmake --build build-test
    cd build-test && ctest --output-on-failure

check:
    nix flake check

run: build
    ./build/my-exe
